### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by MidnightRocket** [SE-E23-SP3/web-technology-project#2]
# Database Table Requirements

## User table
- **Serial id**, `Primary key`
- **Username** `varchar(x), UNIQE, NOT NULL`
- **Password** `char(256) NOT NULL`. _Important that it is a fixed length. Because hashes are always fixed length. And fixed length fields are more performant when relevant._
- **Email**, `varchar(x), UNIQE, NOT NULL`
- **Created at**, `timestamp default`

## Person Table
- **Serial id**, `Primary Key`
- **First name**, `varchar(x)`
- **Last name**, `varchar(x)`

## Movie Table
- **Serial id**, `Primary key`
- **Title**, `varchar(x), NOT NULL`
- **Description**, `varchar(x)`
- **Release Date**, `date`
- **poster_url**, `varchar(x)` *url to image*
- **Overall Rating** *Either as computed entity or dynamic calculated on request*

## Genre Table
- **Serial id**, `Primary key`
- **Genre Name**, `varchar(x)`

## Crew Type Table
- **Serial id**, `Primary key`
- **type**, `varchar(x)`

# The Inbetween Tables

## Movie Cast Table
- **Person id**, `composite key, Foreign Key`
- **Role**, `varchar(x), composite key`
- **Movie id**, `composite key, Foreign Key`

## Movie Genre Table
- **Genre id**, `composite key, Foreign Key`
- **Movie id**, `composite key, Foreign Key`

## Movie Crew Table
- **Person id**, `composite key, Foreign Key`
- **CrewType id**, `composite key, Foreign Key`
- **Movie id**, `composite key, Foreign Key`

## Movie Rating Table
- **User id**, `composite key`
- **Movie id**, `composite key`
- **Rating**, `number`

## Trailers Table
- **serial_id**, `Primary Key`
- **movie_id**, `Foreign Key`
- **url_path**, `varchar(x)`

# Enter the database using the terminal

1. First enter the container using docker compose when in project folder
```
sudo docker compose exec -it postgres bash
```
2. Then run this command, to enter the postgres database 
```
psql -U laravel -d laravel
```

# Seeding the database

> needs to be in the container

To fill the database with data use this command, when used twice it will fill the database with entries until it reaches a copy where its not allowed, columns with the unique modifier, and stop.
```
php artisan db:seed
```
To refresh the database, this deletes all tables and recreates them without entries
```
php artisan migrate:refresh
```

**Comment by Paknu22** [comment]
![Image](https://github.com/SE-E23-SP3/web-technology-project/assets/112689802/c95ba4ac-1035-4283-86dc-a5a7fce1b997)
